[package]
name = "leet_code"
version = "0.1.0"
authors = ["liyanhrxy <838698032@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
